display_name: my-hpt-job
trial_job_spec:
  worker_pool_specs:
    - machine_spec:
        machine_type: n1-standard-4
      replica_count: 1
      container_spec:
        image_uri: gcr.io/your-project/subu:nya
  parameter_spec:
    algorithm: RANDOM_SEARCH
    parameters:
      - double_value_spec:
          min_value: 0.01
          max_value: 0.1
          scale_type: UNIT_LOG_SCALE
          parameter_name: learning_rate
      - double_value_spec:
          min_value: 0
          max_value: 1
          scale_type: UNIT_LINEAR_SCALE
          parameter_name: momentum
      - discrete_value_spec:
          values: [64, 128, 512]
          parameter_name: num_neurons
  measurement_spec:
    metrics:
      - metric_id: accuracy
        goal: MAXIMIZE