trainingInput:
  scaleTier: CUSTOM
  masterType: n1-standard-4
  workerType: n1-standard-4
  parameterServerType: n1-standard-4
  workerCount: 55
  parameterServerCount: 55
  masterConfig:
    imageUri: gcr.io/PROJECT_ID/moso:cok