trainingInput:
  scaleTier: CUSTOM
  masterType: n1-standard-4
  workerType: n1-standard-4
  parameterServerType: n1-standard-4
  workerCount: 55
  parameterServerCount: 55
  hyperparameters:
    goal: MAXIMIZE
    params:
    - parameterName: learning_rate
      minValue: 0.01
      maxValue: 1
      type: DOUBLE
    - parameterName: momentum
      minValue: 0
      maxValue: 1
      type: DOUBLE
    - parameterName: num-neurons
      type: DISCRETE
      discreteValues:
      - 512
    maxTrials: 5000
    maxParallelTrials: 1
    hyperparameterMetricTag: Accuracy
    algorithm: RANDOM_SEARCH
  region: us-central1
  masterConfig:
    imageUri: gcr.io/PROJECT_ID/subu:nya